import math
x=int(input("Enter a number:"))
y=abs(x)
print("The absolute value is:",y)
z=math.ceil(x)
print("The ceiling is:",z)
y=int(input("Enter a number:"))
a=math.exp(x)
print("The exponention is:",a)
b=math.fabs(x)
print("The absolute is:",b)
c=math.floor(x)
print("The largest integer:",c)
d=math.log(x)
print("The logarithm of number is:",d)
e=math.log10(x)
print("The base-10 logarithm is:",e)
f=max(x,y)
print("The largest of arguments is:",f)
g=min(x,y)
print("The smallest of arguments :",g)
h=math.modf(x)
print("The modfx",h)
i=pow(x,y)
print("The value of x*y:",i)
j=math.sqrt(x)
print("The sqrt of x:",j)
